# Generated by Django 3.0.3 on 2020-10-09 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201009_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 18, 1, 54, 514113, tzinfo=utc)),
        ),
    ]
