# Generated by Django 3.0.3 on 2020-10-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201013_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
