# Generated by Django 3.0.3 on 2020-10-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_address',
            field=models.TextField(default='nic'),
            preserve_default=False,
        ),
    ]
