# Generated by Django 3.0.3 on 2020-10-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_video_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_address',
        ),
    ]
