# Generated by Django 3.0.3 on 2020-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_video_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_address',
            field=models.TextField(null=True),
        ),
    ]
