# Generated by Django 3.0.3 on 2020-10-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_video_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post_text',
        ),
    ]
