# Generated by Django 3.0.3 on 2020-10-15 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='main',
        ),
        migrations.AlterField(
            model_name='post',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='blog.Project'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
